/**
 * Gerat Leadership & Engineering Team Dataset (Spec §30, Content Replacement §9)
 * 5 Founders United: Executive leadership aligned with the official brand charter.
 */
export const leadershipTeam = [
  {
    name: "HRUY DANIEL",
    role: "FOUNDER & CHIEF EXECUTIVE OFFICER",
    specialty: "STRATEGY, BRAND POSITIONING & VENTURE",
    bio: "Directs Gerat's vision, partnerships, and business growth, helping organizations turn strategy into reliable digital ventures.",
    email: "hruydaniel@gerat.com",
    phone: "+2519 2929 8030",
    telegramUrl: "https://t.me/geratsolutions",
    whatsappUrl: "https://wa.me/251929298030",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: "/image/team/leadership/hiruy.jpeg",
  },
  {
    name: "EKD",
    role: "CO-FOUNDER & CHIEF OPERATING OFFICER",
    specialty: "OPERATIONS, STRATEGIC EXECUTION & CLIENT DELIVERY",
    bio: "Oversees company-wide execution, strategic program management, and operational delivery across all engineering and client ventures.",
    email: "ekd@gerat.com",
    telegramUrl: "https://t.me/geratsolutions",
    whatsappUrl: "https://wa.me/251929298030",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: "/image/team/leadership/EKD.jpg",
  },
  {
    name: "DAWIT TEKLEBRHAN",
    role: "CO-FOUNDER & CHIEF TECHNOLOGY OFFICER",
    specialty: "SYSTEMS ARCHITECTURE & DIGITAL EXPERIENCES",
    bio: "Leads engineering and technical architecture, focusing on reliable digital products, intelligent tools, and business systems.",
    email: "dawit@gerat.com",
    telegramUrl: "https://t.me/geratsolutions",
    whatsappUrl: "https://wa.me/251929298030",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: "/image/team/leadership/Dawit.jpeg",
  },
  {
    name: "YOHANNES TADESSE",
    role: "CO-FOUNDER & HEAD OF ARTIFICIAL INTELLIGENCE",
    specialty: "APPLIED AI, KNOWLEDGE SYSTEMS & AUTOMATION",
    bio: "Guides applied artificial intelligence and data systems, building practical tools that make information accessible and actionable.",
    email: "yohannes@gerat.com",
    telegramUrl: "https://t.me/geratsolutions",
    whatsappUrl: "https://wa.me/251929298030",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: "/image/team/leadership/Nisiha.jpeg",
  },
  {
    name: "SOLOMON KASSAHUN",
    role: "CO-FOUNDER & HEAD OF ENTERPRISE ENGINEERING",
    specialty: "BUSINESS SYSTEMS, DISTRIBUTED CLOUD & INTEGRATIONS",
    bio: "Oversees business platforms, operations engineering, and secure system integrations that keep company workflows running smoothly.",
    email: "solomon@gerat.com",
    telegramUrl: "https://t.me/geratsolutions",
    whatsappUrl: "https://wa.me/251929298030",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: "/image/team/leadership/hosea.jpeg",
  },
];

export const engineeringSpecialists = [];

