/**
 * Gerat Leadership & Engineering Team Dataset (Spec §30, Content Replacement §9)
 * 5 Founders United: Executive leadership aligned with the official brand charter.
 */
export const leadershipTeam = [
  {
    name: "HRUY DANIEL",
    role: "FOUNDER & CHIEF EXECUTIVE OFFICER",
    specialty: "GENERAL MANAGEMENT · STRATEGY & VENTURE",
    bio: "Directs Gerat's vision, partnerships, and business growth, helping organizations turn strategy into reliable digital ventures.",
    email: "hruydaniel@gerat.com",
    phone: "+2519 2929 8030",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: "/image/team/leadership/hiruy.jpeg",
  },
  {
    name: "EKD",
    role: "CO-FOUNDER & CHIEF OPERATING OFFICER",
    specialty: "OPERATIONS & STRATEGIC EXECUTION",
    bio: "Oversees company-wide execution, strategic program management, and operational delivery across all engineering and client ventures.",
    email: "ekd@gerat.com",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: "/image/team/leadership/EKD.jpg",
  },
  {
    name: "DAWIT TEKLEBRHAN",
    role: "CO-FOUNDER & CHIEF TECHNOLOGY OFFICER",
    specialty: "SYSTEMS ARCHITECTURE · COMPUTATIONAL PLATFORMS",
    bio: "Leads engineering and technical architecture, focusing on reliable digital products, intelligent tools, and business systems.",
    email: "dawit@gerat.com",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: "/image/team/leadership/Dawit.jpeg",
  },
  {
    name: "YOHANNES TADESSE",
    role: "CO-FOUNDER & HEAD OF ARTIFICIAL INTELLIGENCE",
    specialty: "APPLIED RAG · VECTOR RETRIEVAL · LLMS",
    bio: "Guides applied artificial intelligence and data systems, building practical tools that make information accessible and actionable.",
    email: "yohannes@gerat.com",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: "/image/team/leadership/Nisiha.jpeg",
  },
  {
    name: "SOLOMON KASSAHUN",
    role: "CO-FOUNDER & HEAD OF ENTERPRISE ENGINEERING",
    specialty: "DISTRIBUTED CLOUD · ERP PLATFORMS · SECURITY",
    bio: "Oversees business platforms, operations engineering, and secure system integrations that keep company workflows running smoothly.",
    email: "solomon@gerat.com",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: "/image/team/leadership/hosea.jpeg",
  },
];

export const engineeringSpecialists = [
  {
    name: "DR. BEREKET TADESSE",
    role: "PRINCIPAL SYSTEMS ARCHITECT",
    discipline: "BACKEND SYSTEMS & CLOUD",
    focus: "Designs reliable database foundations, data pipelines, and scalable backend infrastructure.",
    email: "bereket@gerat.com",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: "/brand/gerat-mark-orange.svg",
  },
  {
    name: "SELAMAWIT HAILE",
    role: "STAFF APPLIED AI RESEARCHER",
    discipline: "INTELLIGENT TOOLS & SEARCH",
    focus: "Develops practical AI assistants, knowledge search engines, and automated document workflows.",
    email: "selamawit@gerat.com",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: "/brand/gerat-mark-orange.svg",
  },
  {
    name: "MIHRET KASSAHUN",
    role: "LEAD CLOUD ORCHESTRATION ENGINEER",
    discipline: "INFRASTRUCTURE & DEPLOYMENT",
    focus: "Manages container environments, automated deployment pipelines, and continuous platform uptime.",
    email: "mihret@gerat.com",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: "/brand/gerat-mark-orange.svg",
  },
  {
    name: "AMANUEL GIRMA",
    role: "HEAD OF PRODUCT SECURITY",
    discipline: "SYSTEM SECURITY & AUDIT",
    focus: "Focuses on application security, role-based access controls, and data integrity compliance.",
    email: "amanuel@gerat.com",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: "/brand/gerat-mark-orange.svg",
  },
  {
    name: "PETER LEE",
    role: "SENIOR EVENT TELEMETRY ARCHITECT",
    discipline: "EVENT STREAMING & ANALYTICS",
    focus: "Builds real-time event aggregation and analytical reporting systems for business operations.",
    email: "peter@gerat.com",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: "/brand/gerat-mark-orange.svg",
  },
  {
    name: "CHRIS MASON",
    role: "PRINCIPAL INTERACTION ENGINEER",
    discipline: "WEB & MOBILE INTERFACES",
    focus: "Engineers responsive, accessible, and high-performance digital experiences across web and mobile.",
    email: "chris@gerat.com",
    linkedinUrl: "https://linkedin.com/company/gerat",
    twitterUrl: "https://x.com/geratsolutions",
    githubUrl: "https://github.com/gerat-technologies",
    image: null,
  },
];
